# -*- coding: utf-8 -*-
"""flask_estimasiberat.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14I5Z4OhU80spqZPIdOWE2z39T0FgelAa
"""

from flask import Flask, request, render_template
import pickle
import os

app = Flask(__name__)

# Lokasi file model
file_path = 'C:/Predict/modelok.pkl'

# Buka file model dalam mode binary read ('rb')
with open(file_path, 'rb') as model_file:
    # Lakukan operasi yang diperlukan pada file (misalnya, load model)
    model = pickle.load(model_file)

# Tentukan direktori template sebagai direktori C:/Predict
template_dir = os.path.abspath('C:/Predict')
app = Flask(__name__, template_folder=template_dir)

@app.route('/')
def index():
    return render_template('index.html', Estimated_Weight=0, Height=0, Width=0, LengthVer=0, LengthDia=0, LengthCro=0)

@app.route('/predict', methods=['POST'])
def predict():
    # Mendapatkan nilai dari form
    Height, Width, LengthVer, LengthDia, LengthCro = [float(x) for x in request.form.values()]

    # Membuat list data
    data = [Height, Width, LengthVer, LengthDia, LengthCro]

    # Melakukan prediksi menggunakan model
    prediction = model.predict([data])
    output = round(float(prediction[0]), 2)

    # Menampilkan hasil prediksi di halaman HTML
    return render_template('index.html', Estimated_Weight=output, Height=Height, Width=Width, LengthVer=LengthVer, LengthDia=LengthDia, LengthCro=LengthCro)

if __name__ == '__main__':
    app.run(debug=True)